### PR TITLE
fix audience env name

### PR DESCRIPTION
**Pull request by github0013**

### CODE REVIEW

**Comment by lbalmaceda** [comment]
Hi 👋 I'm not 100% sure about this PR since there are still other search results for `AUTH0_AUDIENCE` if you check. Can you please change all of them?

**Comment by github0013** [comment]
https://github.com/auth0-samples/auth0-rubyonrails-api-samples/blob/88e3179a33094b4412f2beff781a32997cb5cc24/01-Authentication-RS256/.env.example#L2

https://github.com/auth0-samples/auth0-rubyonrails-api-samples/blob/88e3179a33094b4412f2beff781a32997cb5cc24/01-Authentication-RS256/config/secrets.yml#L16

.env and secret.yml are using different key names.



[Because jwt gem only checks when there is `aud` value][1], and this part is `nil` (the key mis-match)

https://github.com/auth0-samples/auth0-rubyonrails-api-samples/blob/88e3179a33094b4412f2beff781a32997cb5cc24/01-Authentication-RS256/lib/json_web_token.rb#L12

the sample code is actually skipping the `aud` verification.

[1]: https://github.com/jwt/ruby-jwt/blob/v2.2.1/lib/jwt/verify.rb#L32

**Comment by lbalmaceda** [comment]
What I'm saying is that this PR is fixing this on one location but there are several other references to `AUTH0_AUDIENCE` that would probably need to be changed to `AUTH0_API_AUDIENCE` as well. None of them belong to the secrets file. See https://github.com/auth0-samples/auth0-rubyonrails-api-samples/search?q=AUTH0_AUDIENCE&unscoped_q=AUTH0_AUDIENCE

**Comment by github0013** [comment]
let me know if anything else is bad.

**Pull request merged**
